### ISSUE TITLE
Cannot read property \'productType\' of undefined

### ISSUE THREAD

**Issue by junajan** [commercetools/commercetools-node-variant-reassignment#82]
Sometimes we get an error when running reassignment:
```
TypeError: Cannot read property \'productType\' of undefined
 at VariantReassignment._callee7$ (/app/node_modules/commercetools-node-variant-reassignment/dist/runner/variant-reassignment.js:730:55)
 at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
 at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
 at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
 at step (/app/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
 at /app/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
```

Error is comming from this line:
https://github.com/commercetools/commercetools-node-variant-reassignment/blob/v1.1.2/lib/runner/variant-reassignment.js#L250

It looks like this error is happening when we split multiple variants to single products.

**Comment by junajan** [comment]
After some investigation, I found this error which is thrown before error mentioned above:
```
{
  hostname: "zeg-product-import-cronjob-1550299200-hknlb"
  level: 50
  msg: "VariantReassignment Error occurred while processing product draft { name: { 'de-DE': 'Kids' },
  slug: {
    'en-AU': 'pegasus-kids-40011',
    'fr-CH': 'pegasus-kids-40011',
    'de-CH': 'pegasus-kids-40011',
    'it-CH': 'pegasus-kids-40011',
    'de-DE': 'pegasus-kids-40011',
    'en-GB': 'pegasus-kids-40011',
    'es-ES': 'pegasus-kids-40011',
    'fr-FR': 'pegasus-kids-40011',
    'it-IT': 'pegasus-kids-40011',
    'nl-NL': 'pegasus-kids-40011',
    'en-NZ': 'pegasus-kids-40011',
    'ru-RU': 'pegasus-kids-40011'
  },
  productType: {
    id: '7028d3c3-5013-495c-9abb-f404263be73c',
    typeId: 'product-type'
  },
  variants: [],
  taxCategory: {
    id: 'c70c52e2-c8e8-405b-9822-7c7c7c3eb731',
    typeId: 'tax-category'
  },
  description: {
    'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
  },
  searchKeywords: {
    'de-DE': [{
      text: 'Kids'
    }, {
      text: 'Kids Ki16 Bl Rh26cm Bana 1N'
    }, {
      text: 'Pegasus'
    }]
  },
  masterVariant: {
    sku: '40011_PANTHER',
    attributes: [{
      name: 'freigabe',
      value: false
    }, {
      name: 'marke',
      value: '270483'
    }, {
      name: 'auslauf',
      value: false
    }, {
      name: 'vorankuendigung',
      value: false
    }, {
      name: 'gesperrt',
      value: false
    }, {
      name: 'haendler_id',
      value: '1021'
    }, {
      name: 'neudatum',
      value: '2030-10-20'
    }, {
      name: 'produktlinie',
      value: '270467'
    }, {
      name: 'laender',
      value: ['DE']
    }, {
      name: 'beschreibung_kurz_online',
      value: {
        'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
      }
    }, {
      name: 'shopbezeichnung',
      value: {
        'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
      }
    }, {
      name: 'nachfolger',
      value: '30022'
    }, {
      name: 'modelljahr',
      value: '2009'
    }, {
      name: 'lieferantensuchname',
      value: 'PANTHER'
    }, {
      name: 'vorgaenger',
      value: '50012'
    }, {
      name: 'warengruppe',
      value: ['111921']
    }, {
      name: 'merkmal_BRHE',
      value: 'BRHE_BR12'
    }, {
      name: 'merkmal_BRVO',
      value: 'BRVO_BR85'
    }, {
      name: 'merkmal_FELG',
      value: 'FELG_F2'
    }, {
      name: 'merkmal_GABE',
      value: 'GABE_UNI'
    }, {
      name: 'merkmal_GANG',
      value: 'GANG_1N'
    }, {
      name: 'merkmal_HRNA',
      value: 'HRNA_HR2'
    }, {
      name: 'merkmal_LENB',
      value: 'LENB_LE5'
    }, {
      name: 'merkmal_PEDA',
      value: 'PEDA_PE6'
    }, {
      name: 'merkmal_RADG',
      value: 'RADG_16'
    }, {
      name: 'merkmal_RHOE',
      value: 'RHOE_26'
    }, {
      name: 'merkmal_RTYP',
      value: 'RTYP_38'
    }, {
      name: 'merkmal_SATT',
      value: 'SATT_SAT1'
    }, {
      name: 'nummer',
      value: '40011'
    }, {
      name: 'referenzartikelnummer',
      value: '40011'
    }],
    prices: [],
    images: [],
    _MATCH_CRITERIA: '40011_PANTHER',
    assets: []
  }
}

{
  ConcurrentModification: Version mismatch. Concurrent modification.
    at /app/node_modules/sphere-node-sdk/lib/services/base.js:512:22
    at ProductService.BaseService._wrapResponse (/app/node_modules/sphere-node-sdk/lib/services/base.js:523:11)
    at /app/node_modules/sphere-node-sdk/lib/services/base.js:400:40
    at Request._callback (/app/node_modules/sphere-node-sdk/lib/connect/rest.js:166:14)
    at Request.self.callback (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:185:22)
    at Request.emit (events.js:189:13)
    at Request.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:189:13)
    at IncomingMessage.<anonymous> (/app/node_modules/sphere-node-sdk/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:277:13)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  message: 'Version mismatch. Concurrent modification.',
  body: {
    http: {
      request: {
        method: 'POST',
        httpVersion: '1.1',
        uri: Url{
          pathname: '/zeg-meier1021-prod/products/830442f0-6af3-4743-81c6-36e8b04846cf',
          path: '/zeg-meier1021-prod/products/830442f0-6af3-4743-81c6-36e8b04846cf',
          href: 'https://api-zeg-at-rackspace.sphere.io/zeg-meier1021-prod/products/830442f0-6af3-4743-81c6-36e8b04846cf'
        },
        response: {
          headers:
          statusCode: 409,
          message: 'Version mismatch. Concurrent modification.',
          errors: [{
            code: 'ConcurrentModification',
            message: 'Version mismatch. Concurrent modification.',
            currentVersion: 126
          }],
          originalRequest: {
            endpoint: '/products/830442f0-6af3-4743-81c6-36e8b04846cf',
            payload: {
              version: 109,
              actions: [{
                action: 'setAttributeInAllVariants',
                name: 'beschreibung_kurz_online',
                value: {
                  'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
                }
              }, {
                action: 'setAttributeInAllVariants',
                name: 'shopbezeichnung',
                value: {
                  'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
                }
              }, {
                action: 'setAttributeInAllVariants',
                name: 'produktlinie',
                value: '270467'
              }, {
                action: 'setAttributeInAllVariants',
                name: 'haendler_id',
                value: '1021'
              }, {
                action: 'setAttributeInAllVariants',
                name: 'vorgaenger',
                value: '50012'
              }, {
                action: 'setAttributeInAllVariants',
                name: 'nachfolger',
                value: '30022'
              }, {
                action: 'setAttributeInAllVariants',
                name: 'marke',
                value: '270483'
              }, {
                action: 'setAttributeInAllVariants',
                name: 'laender',
                value: ['DE']
              }, {
                action: 'setAttributeInAllVariants',
                name: 'warengruppe',
                value: ['111921']
              }, {
                action: 'setAttributeInAllVariants',
                name: 'neudatum',
                value: '2030-10-20'
              }, {
                action: 'addVariant',
                sku: '40011_PANTHER',
                key: undefined,
                prices: [],
                images: [],
                attributes: [{
                  name: 'freigabe',
                  value: false
                }, {
                  name: 'marke',
                  value: '270483'
                }, {
                  name: 'auslauf',
                  value: false
                }, {
                  name: 'vorankuendigung',
                  value: false
                }, {
                  name: 'gesperrt',
                  value: false
                }, {
                  name: 'haendler_id',
                  value: '1021'
                }, {
                  name: 'neudatum',
                  value: '2030-10-20'
                }, {
                  name: 'produktlinie',
                  value: '270467'
                }, {
                  name: 'laender',
                  value: ['DE']
                }, {
                  name: 'beschreibung_kurz_online',
                  value: {
                    'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
                  }
                }, {
                  name: 'shopbezeichnung',
                  value: {
                    'de-DE': 'Kids Ki16 Bl Rh26cm Bana 1N'
                  }
                }, {
                  name: 'nachfolger',
                  value: '30022'
                }, {
                  name: 'modelljahr',
                  value: '2009'
                }, {
                  name: 'lieferantensuchname',
                  value: 'PANTHER'
                }, {
                  name: 'vorgaenger',
                  value: '50012'
                }, {
                  name: 'warengruppe',
                  value: ['111921']
                }, {
                  name: 'merkmal_BRHE',
                  value: 'BRHE_BR12'
                }, {
                  name: 'merkmal_BRVO',
                  value: 'BRVO_BR85'
                }, {
                  name: 'merkmal_FELG',
                  value: 'FELG_F2'
                }, {
                  name: 'merkmal_GABE',
                  value: 'GABE_UNI'
                }, {
                  name: 'merkmal_GANG',
                  value: 'GANG_1N'
                }, {
                  name: 'merkmal_HRNA',
                  value: 'HRNA_HR2'
                }, {
                  name: 'merkmal_LENB',
                  value: 'LENB_LE5'
                }, {
                  name: 'merkmal_PEDA',
                  value: 'PEDA_PE6'
                }, {
                  name: 'merkmal_RADG',
                  value: 'RADG_16'
                }, {
                  name: 'merkmal_RHOE',
                  value: 'RHOE_26'
                }, {
                  name: 'merkmal_RTYP',
                  value: 'RTYP_38'
                }, {
                  name: 'merkmal_SATT',
                  value: 'SATT_SAT1'
                }, {
                  name: 'nummer',
                  value: '40011'
                }, {
                  name: 'referenzartikelnummer',
                  value: '40011'
                }]
              }]
            },
            options: {
              config: {
                project_key: 'zeg-meier1021-prod'
              },
              host: 'api-zeg-at-rackspace.sphere.io',
              protocol: 'https',
              timeout: 360000,
              rejectUnauthorized: true,
            }
          },
          name: 'ConcurrentModification',
          statusCode: 409,
          code: 409,
          name: "zeg-cli-0.48.5"
          projectId: "9999999"
          projectKey: "zeg-master-prod-2016"
          widget_type: "product-import"
        }
      }
    }
  }
```

**Comment by junajan** [comment]
In [this case](https://console.cloud.google.com/logs/viewer?interval=CUSTOM&project=customer-zeg&authuser=1&minLogLevel=0&expandAll=false&timestamp=2019-02-16T07:36:29.333000000Z&customFacets=&limitCustomFacetWidth=true&scrollTimestamp=2019-02-16T07:36:29.333000000Z&dateRangeStart=2019-02-16T07:36:20.000Z&dateRangeEnd=2019-02-16T07:36:42.000Z&advancedFilter=resource.type%3D%22container%22%0Aresource.labels.cluster_name%3D%22zeg-production%22%0Aresource.labels.namespace_id%3D%22default%22%0Aresource.labels.project_id%3D%22customer-zeg%22%0Aresource.labels.zone:%22europe-west1-%22%0Aresource.labels.container_name%3D%22cronjob%22%0Aresource.labels.pod_id%3D%22zeg-product-import-cronjob-1550299200-hknlb%22%0AinsertId%3D%22y4zattfllxyd5%22%0Aseverity%3E%3DDEBUG) we got a productDraft containing SKU `40011_AAA` and SLUG `ABCD-40011` and we run an import with it:
 - ProductImporter did not find any matching product by SKU so it tried to create it but it failed due to a `Duplicate SLUG` error.
 - This error triggered a variant reassignment which fetched conflicting product using SLUG and generated `addVariant` action (first it generated also `update sameForAll attributes` so it can add new variant). Later it would also want to move old variant with SKU `40012_AAA` to anonymized product.
 - In the meantime there was imported product with SKU `40012_AAA` which also changed slug to `ABCD-40012`.
 - When executing reassignment update actions on CTP API it got concurrent modification error
 - It fetched transaction object and tried to fetch again matching products but this time it returned an empty array and thus, [when selecting](https://github.com/commercetools/commercetools-node-variant-reassignment/blob/v1.1.2/lib/runner/variant-reassignment.js#L233) `ctpProductToUpdate`, it returned `undefined`.
 - Later it checked whether there was a productType change by checking `ctpProductToUpdate.productType.id` property which threw the error mentioned above:
```
TypeError: Cannot read property \'productType\' of undefined
```

Fix for this issue should contain a check whether the `ctpProductToUpdate` exists and if not we should stop reassignment and let product importer to create productDraft as a new product.
